version: '3.7'
services:

  recipe:
    container_name: recipe
    build:
      context: .
    ports:
    - 8080:8080
    networks:
      - my-network
    depends_on:
      - db

  db:
    image: mysql:5.7
    volumes:
      - ./volume:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "controle_receitas"
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_USER: "lucas"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge